spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notdb?useSSL=false&serverTimezone=UTC
    username: sa         # kendi MySQL kullanıcı adını yaz
    password: 123456789         # kendi MySQL şifreni yaz

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    cache: false
    enabled=true:

server:
  port: 8080
